webtalk_init -webtalk_dir C:/Users/Win10Admin/GithubRepositories/DNN/vivado/DNN/DNN.sim/sim_1/behav/xsim/xsim.dir/DNN_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 22 20:23:39 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "196ea172-ff88-412b-a40b-dff319270d5c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "01688a18fb6349ac85fe3b09858f19e4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "21" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "577 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "214 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1845" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "258" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "ieee_proposed secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "32.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "273316_KB" -context "xsim\\usage"
webtalk_transmit -clientid 614539702 -regid "" -xml C:/Users/Win10Admin/GithubRepositories/DNN/vivado/DNN/DNN.sim/sim_1/behav/xsim/xsim.dir/DNN_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Win10Admin/GithubRepositories/DNN/vivado/DNN/DNN.sim/sim_1/behav/xsim/xsim.dir/DNN_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Win10Admin/GithubRepositories/DNN/vivado/DNN/DNN.sim/sim_1/behav/xsim/xsim.dir/DNN_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
